apiVersion: v1
kind: Service
metadata:
  name: purger
  labels:
    name: rpaas-purger
spec:
  ports:
  - name: purger
    port: 9990
    targetPort: 9990
  selector:
    name: rpaas-purger
  type: LoadBalancer
